---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: _snippets/intro.md
  label: Intro
- type: directory
  path: _reviews
  label: Reviews
  create: documents
  match: "**/*"
  templates:
  - review
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
